version: '2'
services:  
  otel_collector:
    container_name: otel
    networks:
      - backend
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    # environment:
    #   DATADOG_KEY: ${DATADOG_KEY}
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317   # OTLP gRPC receiver
      - 4318:4318   # OTLP http receiver
    restart: always
    depends_on:
      - jaeger

  jaeger:
    networks:
      - backend
    image: jaegertracing/all-in-one:latest
    # volumes:
    #   - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    # command: --query.ui-config /etc/jaeger/jaeger-ui.json
    # environment:
    #   - METRICS_STORAGE_TYPE=prometheus
    #   - PROMETHEUS_SERVER_URL=http://prometheus:9090
    ports:
      - 16686:16686
      - 14269:14269 # http://localhost:14269/metrics
    restart: always

networks:
  backend:
