version: '2'
services:
  proxy:
    image: ubuntu/squid
    ports:
      - "6565:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./passwordss:/etc/squid/passwords
    restart: always