up:
	docker compose up -d
down:
	docker compose down
ps:
	docker ps -a
exec:
	docker exec -it kafka sh

# /opt/kafka_2.13-2.8.1/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic metrics
